int dni = Funciones.IngresarEntero("Ingrese su DNI");
string ape = Funciones.IngresarTexto("Ingresar su apellido ");
string nomb = Funciones.IngresarTexto("Ingrese su nombre "); 
DateTime fecha = Funciones.IngresarFecha("Ingrese la fecha de inscripcion dd/mm/yyyy");
int tipoEnt = Funciones.IngresarEnteroEnRango("Ingrese el tipo de entrada",1,4);
Console.WriteLine("Opción 1 - Día 1 , valor a abonar $15000");
Console.WriteLine("Opción 2 - Día 2, valor a abonar $30000");
Console.WriteLine("Opción 3 - Día 3, valor a abonar $10000");
Console.WriteLine("Opción 4 - Full Pass, valor a abonar $40000");
int TotalAbon = Funciones.AbonoTotal(tipoEnt);
Cliente cliente = new Cliente(dni,ape,nomb,fecha,tipoEnt,TotalAbon);
Ticketera.DicClientes.Add(Ticketera.UltimoIDEntrada,cliente);